name: mirrorchyan_release_note

on:
  workflow_dispatch:
  release:
    types: [edited]

jobs:
  mirrorchyan_release_note:
    runs-on: macos-latest

    steps:
      - uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: ASU_moe

          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
